import Head from "next/head";
import VercelLogo from "next/image";
import Styles from "../../styles/home.module.css";

export default function AnalyticsCoreV4() {
  return (
    <div className={Styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={Styles.main}>
        <h1 className={Styles.title}>
          Welcome to <a href="https://nextjs.org">Core-v4 Page</a>
        </h1>

        <p className={Styles.description}>
          Get started by editing{" "}
          <code className={Styles.code}>pages/analytics/corev4.tsx</code>
        </p>

        <div className={Styles.grid}>
          <a href="https://nextjs.org/docs" className={Styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Here is where a graph of analytics could go</p>
          </a>

          <a href="https://nextjs.org/learn" className={Styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>
      </main>

      <footer className={Styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={Styles.logo}>
            <VercelLogo src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
